package com.sillyhusky.base64.cp

class Base64CPDotMaps : Base64CPMaps {

    companion object {
        private val instance = Base64CPDotMaps()
        fun default(): Base64CPMaps {
            return instance
        }

        private val binToCharMap: Map<Int, Int> = mapOf(
            0 to '.'.code /* Full Stop (Period) */,
            1 to ':'.code /* Colon */,
            2 to ';'.code /* Semicolon */,
            3 to ','.code /* Comma */,
            4 to '-'.code /* Hyphen-Minus */,
            5 to '·'.code /* Middle Dot */,
            6 to '•'.code /* Bullet */,
            7 to '․'.code /* One Dot Leader */,
            8 to '‧'.code /* Hyphenation Point */,
            9 to '∙'.code /* Bullet Operator */,
            10 to '‐'.code /* Hyphen */,
            11 to '‑'.code /* Non-Breaking Hyphen */,
            12 to '‒'.code /* Figure Dash */,
            13 to '⋅'.code /* Dot Operator */,
            14 to '*'.code /* Asterisk */,
            15 to '÷'.code /* Division Sign */,
            16 to '⋇'.code /* Division Times */,
            17 to '⋈'.code /* Bowtie */,
            18 to '‼'.code /* Double Exclamation Mark */,
            19 to '⁃'.code /* Hyphen Bullet */,
            20 to '⁄'.code /* Fraction Slash */,
            21 to '⁅'.code /* Left Square Bracket With Quill */,
            22 to '⁆'.code /* Right Square Bracket With Quill */,
            23 to '⁇'.code /* Double Question Mark */,
            24 to '⁈'.code /* Question Exclamation Mark */,
            25 to '⁉'.code /* Exclamation Question Mark */,
            26 to '⁊'.code /* Tironian Sign Et */,
            27 to '⁋'.code /* Reversed Pilcrow Sign */,
            28 to '⁌'.code /* Black Leftwards Bullet */,
            29 to '⁍'.code /* Black Rightwards Bullet */,
            30 to '⁝'.code /* Tricolon */,
            31 to '⁞'.code /* Vertical Four Dots */,
            32 to '≅'.code /* Approximately Equal To */,
            33 to '″'.code /* Double Prime */,
            34 to '¦'.code /* Broken Bar */,
            35 to '¯'.code /* Macron */,
            36 to '˄'.code /* Modifier Letter Up Arrowhead */,
            37 to '˅'.code /* Modifier Letter Down Arrowhead */,
            38 to 'ˆ'.code /* Modifier Letter Circumflex Accent */,
            39 to 'ˇ'.code /* Caron */,
            40 to 'ˉ'.code /* Modifier Letter Macron */,
            41 to 'ˍ'.code /* Modifier Letter Low Macron */,
            42 to '˜'.code /* Small Tilde */,
            43 to '˗'.code /* Modifier Letter Minus Sign */,
            44 to '˘'.code /* Breve */,
            45 to '˙'.code /* Dot Above */,
            46 to '˚'.code /* Ring Above */,
            47 to '˛'.code /* Ogonek */,
            48 to '˝'.code /* Double Acute Accent */,
            49 to '̃'.code /* Combining Tilde */,
            50 to '̄'.code /* Combining Macron */,
            51 to '̅'.code /* Combining Overline */,
            52 to '̇'.code /* Combining Dot Above */,
            53 to '̉'.code /* Combining Hook Above */,
            54 to '̣'.code /* Combining Dot Below */,
            55 to '̲'.code /* Combining Low Line */,
            56 to '̶'.code /* Combining Long Stroke Overlay */,
            57 to '̷'.code /* Combining Short Solidus Overlay */,
            58 to '̸'.code /* Combining Long Solidus Overlay */,
            59 to '±'.code /* Plus-Minus Sign */,
            60 to '¬'.code /* Not Sign */,
            61 to '≡'.code /* Identical To */,
            62 to '¸'.code /* Cedilla */,
            63 to '‗'.code /* Double Low Line */
        )

        private val charToBinMap: Map<Int, Int> = mapOf(
            '.'.code to 0,
            ':'.code to 1,
            ';'.code to 2,
            ','.code to 3,
            '-'.code to 4,
            '·'.code to 5,
            '•'.code to 6,
            '․'.code to 7,
            '‧'.code to 8,
            '∙'.code to 9,
            '‐'.code to 10,
            '‑'.code to 11,
            '‒'.code to 12,
            '⋅'.code to 13,
            '*'.code to 14,
            '÷'.code to 15,
            '⋇'.code to 16,
            '⋈'.code to 17,
            '‼'.code to 18,
            '⁃'.code to 19,
            '⁄'.code to 20,
            '⁅'.code to 21,
            '⁆'.code to 22,
            '⁇'.code to 23,
            '⁈'.code to 24,
            '⁉'.code to 25,
            '⁊'.code to 26,
            '⁋'.code to 27,
            '⁌'.code to 28,
            '⁍'.code to 29,
            '⁝'.code to 30,
            '⁞'.code to 31,
            '≅'.code to 32,
            '″'.code to 33,
            '¦'.code to 34,
            '¯'.code to 35,
            '˄'.code to 36,
            '˅'.code to 37,
            'ˆ'.code to 38,
            'ˇ'.code to 39,
            'ˉ'.code to 40,
            'ˍ'.code to 41,
            '˜'.code to 42,
            '˗'.code to 43,
            '˘'.code to 44,
            '˙'.code to 45,
            '˚'.code to 46,
            '˛'.code to 47,
            '˝'.code to 48,
            '̃'.code to 49,
            '̄'.code to 50,
            '̅'.code to 51,
            '̇'.code to 52,
            '̉'.code to 53,
            '̣'.code to 54,
            '̲'.code to 55,
            '̶'.code to 56,
            '̷'.code to 57,
            '̸'.code to 58,
            '±'.code to 59,
            '¬'.code to 60,
            '≡'.code to 61,
            '¸'.code to 62,
            '‗'.code to 63
        )

    }

    override fun getBinToCharMap(): Map<Int, Int> {
        return binToCharMap
    }

    override fun getCharToBinMap(): Map<Int, Int> {
        return charToBinMap
    }

}